# Generated by Django 4.2.11 on 2024-03-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('1', 'Танки'), ('2', 'Хилы'), ('3', 'ДД'), ('4', 'Торговцы'), ('5', 'Гилдмастеры'), ('6', 'Квестгиверы'), ('7', 'Кузнецы'), ('8', 'Кожевники'), ('9', 'Зельевары'), ('10', 'Мастера_заклинаний')], max_length=20),
        ),
    ]
