# Generated by Django 4.2.11 on 2024-04-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0003_remove_foto_post_postfoto_post_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='image',
            field=models.ImageField(blank=True, upload_to='foto'),
        ),
    ]
