# Generated by Django 4.2.11 on 2024-04-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0004_alter_foto_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='foto',
        ),
        migrations.AlterField(
            model_name='foto',
            name='image',
            field=models.ImageField(blank=True, unique=True, upload_to='foto'),
        ),
        migrations.DeleteModel(
            name='PostFoto',
        ),
    ]
