# Generated by Django 4.2.11 on 2024-04-02 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0005_remove_post_foto_alter_foto_image_delete_postfoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='appcore.post'),
        ),
    ]
