# Generated by Django 4.2.11 on 2024-04-02 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0006_foto_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='post',
        ),
        migrations.CreateModel(
            name='PostFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcore.foto')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcore.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='foto',
            field=models.ManyToManyField(through='appcore.PostFoto', to='appcore.foto'),
        ),
    ]
