# Generated by Django 4.2.11 on 2024-04-02 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0007_remove_foto_post_postfoto_post_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='post',
        ),
        migrations.RemoveField(
            model_name='video',
            name='post',
        ),
        migrations.CreateModel(
            name='PostVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcore.post')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcore.video')),
            ],
        ),
        migrations.CreateModel(
            name='PostFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcore.file')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcore.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.ManyToManyField(through='appcore.PostFile', to='appcore.file'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.ManyToManyField(through='appcore.PostVideo', to='appcore.video'),
        ),
    ]
